(function(g){var window=this;var R8=function(a,b){var c=a.getAttribute(b);if(null!=c)return(0,window.parseFloat)(c)},S8=function(a){var b=1+.25*(a.Og||0);
if(0==a.offset||2==a.offset)b*=.8;return b},T8=function(a){if(!exa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(fxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},U8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return g.Nu.test(c),c},V8=function(a,b){var c=R8(a,b);
if(void 0!=c)return c},W8=function(a,b){var c={};
if(null!=b.Pd||b.background){var d=null!=b.Pd?b.Pd:a.o.Za.Pd,e=T8(b.background?b.background:a.o.Za.background);c.background="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")";a.ha&&(c["box-decoration-break"]="clone",c["border-radius"]=a.W/8+"px")}if(null!=b.Og||null!=b.offset)c["font-size"]=a.aa*S8(b)+"px";d=1;if(b.color||null!=b.Rf)e=T8(b.color||a.o.Za.color),d=null==b.Rf?a.o.Za.Rf:b.Rf,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;if(null!=b.ef&&0!=b.ef){e="rgba(34, 34, 34, "+d+")";d="rgba(204, 204, 204, "+
d+")";b.xr&&(d=e=b.xr);var f;switch(b.ef){case 4:f="2px 2px 3px "+e+", 2px 2px 4px "+e+", 2px 2px 5px "+e;break;case 1:f="1px 1px "+e+", 2px 2px "+e+", 3px 3px "+e;break;case 2:f="1px 1px "+d+", 0 1px "+d+", -1px -1px "+e+", 0 -1px "+e;break;case 3:f="0 0 4px "+e+", 0 0 4px "+e+", 0 0 4px "+e+", 0 0 4px "+e}c["text-shadow"]=f}f="";switch(b.fontFamily){case 1:f='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:f='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';
break;case 3:f='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:f='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:f='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:f=g.Lh()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:f='Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}f&&
(c["font-family"]=f);f=b.offset;null==f&&(f=a.o.Za.offset);switch(f){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Zn&&(c["font-style"]="italic");b.Jo&&(c["text-decoration"]="underline");b.vn&&(c.visibility="hidden");return c},X8=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Y8=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.wa(c,a.jw[d]);d=V8(b,"ap");null!=d&&(c.gg=d);d=R8(b,"cc");null!=d&&(c.Er=d);d=R8(b,"ah");null!=d&&(c.jh=d);d=R8(b,"rc");null!=d&&(c.Ui=d);d=R8(b,"av");null!=d&&(c.Ch=d);return c},Z8=function(a,b,c){var d={},e=c.getAttribute("ws");
g.wa(d,e?b.kw[e]:a.A);a=V8(c,"mh");null!=a&&(d.ao=a);a=V8(c,"ju");null!=a&&(d.textAlign=a);a=V8(c,"pd");null!=a&&(d.Bh=a);a=U8(c,"wfc");null!=a&&(d.windowColor=a);c=R8(c,"wfo");void 0!=c&&(d.Gh=c/255);return d},$8=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Zn=!0;break;case "u":k.Jo=!0;break;case "font":var m=f.getAttribute("color");g.Nu.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new g.Fu(a,b,c,d,n.nodeValue,e||0<m,g.Pb(k)?void 0:k));else{var r={};g.wa(r,k);$8(a,b,c,d,e||0<m,n,r,l)}}},gxa=function(){this.A=[];
this.g=[];this.o=-1},a9=function(a,b,c){a.H=a.H||!!c;
var d={};g.wa(d,a.o.Za);g.wa(d,c||b.o);g.wa(d,a.pa.Za);var e=a.F[0],f;if(e&&d.background==e.background&&d.Pd==e.Pd&&!!d.vn==!!e.vn&&d.ef==e.ef){for(c=0;c<a.F.length;c++)if(X8(d,a.F[c])){f=a.G[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.Le("SPAN");g.wl(f,W8(a,c));a.G[0].appendChild(f);c=1}a.G.length=c;a.F.length=c}else a.G.length=0,a.F.length=0,f=g.Le("SPAN"),g.wl(f,W8(a,d)),a.B.appendChild(f);a.D&&a.D.parentNode!=f&&(g.Re(a.D),f.appendChild(a.D));e=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.C.length||!b.D){if(0<c||0!=a.C.length){var m=g.Le("BR");f.appendChild(m)}f.appendChild(g.Me("\u00a0"));a.D=g.Me("\u00a0");f.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.Me(l):l,m))}a.F.push(d);a.G.push(f);a.C.push(b)},b9=function(a){if(a.A.captionTracks.length){var b=a.g.mj().rr;
if(2==b||3==b)return!0}return 1==a.V.pa||1==a.A.Sq||"alwayson"==a.A.Fe("yt:cc")?!0:2==a.V.pa&&(b=g.Qu(a,"module-enabled"),null!=b)?!!b:"on"==a.A.Fe("yt:cc")},c9=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},d9=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Zn=!0;break;case "u":l.Jo=!0}for(var n=0;n<k.childNodes.length;n++){var r=k.childNodes[n];if(3==r.nodeType)r=new g.Fu(b,c,d,e.id,r.nodeValue,f||0<n,g.Pb(l)?void 0:l),m.push(r),e!=a.A&&e.Wh.push(r);else{var u={};g.wa(u,l);d9(a,b,c,d,e,!0,r,u,m)}}},e9=function(a,b,c,d){var e={};
g.wa(e,Y8(b,c));g.wa(e,Z8(a,b,c));d?(b="_"+g.Hu++,X8(e,a.A)&&(e=a.A)):b=c.getAttribute("id")||"0";a=R8(c,"t");c=R8(c,"d")||0x8000000000000;return new g.Gu(a,c,0,b,e)},f9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},g9=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.bp("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");$8(d,e,k,b,f,a.firstChild,{},c)},h9=function(){this.o=[];
this.g=[]},i9=function(a){if(!a.J){var b=g.Le("SPAN");
g.wl(b,W8(a,a.o.Za));a.B.appendChild(b);b.appendChild(g.Me("M"));var c=b.offsetHeight,d=g.Le("BR");b.appendChild(d);b.appendChild(g.Me("M"));a.J=b.offsetHeight-c;a.B.removeChild(b)}return a.J},j9=function(){this.ya=[]},k9=function(a){this.At=!!a;
this.g=new gxa;this.C=[]},l9=function(a,b){g.Xa(b,(0,g.w)(a.J,a))||b.push(a)},m9=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];
g.v(d.text)&&(b+=d.text.split("\n").length-1,d.D||0==c||b++)}return b},n9=function(a,b,c,d,e,f){this.C=[];
this.H=!1;this.A=a;this.F=[];this.G=[];this.xa=e;this.sa=f;this.D=null;this.O=.96*e;this.la=.96*f;this.o={};g.wa(this.o,b);g.wa(this.o,this.A.params);g.wa(this.o,c);e={};g.wa(e,b.Za);this.A.params.Za&&g.wa(e,this.A.params.Za);g.wa(e,c.Za);this.o.Za=e;this.pa=c;g.R.call(this,{K:"div",Y:"caption-window",X:{id:"caption-window-"+a.id,dir:1==this.o.Bh?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:this.o.lang},R:[{K:"span",Y:"captions-text"}]});this.B=this.ua["captions-text"];this.ha=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.W=this.aa*S8(e);a=new g.wu(this.element,!0);g.K(this,a);a.subscribe("dragstart",this.jL,this);a.subscribe("dragmove",this.iL,this);a.subscribe("dragend",this.hL,this);this.da=this.ca=0;a="";this.o.Gh&&(a=T8(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Gh+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":hxa[this.o.textAlign]};this.ha&&(b["border-radius"]=a?this.W/
8+"px":"");g.wl(this.element,b);switch(this.o.gg){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},p9=function(a){return g.Ju(a)?!a.A.o:a.A.captionTracks.length&&a.g.mj().dk?!0:b9(a)},r9=function(a,b){h9.call(this);
this.A=g.Iu({ao:0});this.g.push(this.A);for(var c=a.split(ixa),d=1;d<c.length;d++){var e=c[d],f=b;if(""!=e&&!jxa.test(e)){var k=g.e8.exec(e);if(k&&3<=k.length){var l=c9(k[1]),k=c9(k[2])-l,e=e.substring(g.e8.lastIndex);g.e8.lastIndex=0;var f=l+f,l=k,m=e,k={},n=this.A,e=5;if(0>m.indexOf("<"))this.o.push(new g.Fu(f,l,e,n.id,m,!1,g.Pb(k)?void 0:k));else{m=m.split(kxa);1!=m.length&&(e=6,n="_"+lxa++,n=new g.Gu(f,l,e,n,{}),this.g.push(n));for(var r=f,u=0;u<m.length;u++){var x=m[u];if(0==u%2){var z=g.bp("<html>"+
x+"</html>"),C;z.getElementsByTagName("parsererror").length?(C=z.createElement("span"),C.appendChild(z.createTextNode(x))):C=z.firstChild;d9(this,r,l-(r-f),e,n,0<u,C,k,this.o)}else r=c9(x)}}}g.e8.lastIndex=0}}},s9=function(a,b){h9.call(this);
a.firstChild.getAttribute("format");this.A=b;for(var c={Qk:{},jw:{},kw:{}},d,e,f=a.firstChild.childNodes,k=0;k<f.length;k++){var l=f[k];switch(l.tagName){case "head":d=l;break;case "body":e=l}}if(d)for(d=d.childNodes,f=0;f<d.length;f++){var m=d[f];switch(m.tagName){case "pen":var l=m.getAttribute("id"),k=c.Qk,n=c,r=m,m={},u=r.getAttribute("p");u&&g.wa(m,n.Qk[u]);n=f9(r,"b");null!=n&&(m.bold=n);n=f9(r,"i");null!=n&&(m.Zn=n);n=f9(r,"u");null!=n&&(m.Jo=n);n=V8(r,"et");null!=n&&(m.ef=n);n=V8(r,"of");
null!=n&&(m.offset=n);n=U8(r,"bc");null!=n&&(m.background=n);n=U8(r,"ec");null!=n&&(m.xr=n);n=U8(r,"fc");null!=n&&(m.color=n);n=V8(r,"fs");void 0!=n&&0!=n&&(m.fontFamily=n);n=R8(r,"sz");void 0!=n&&(m.Og=n/100-1);n=R8(r,"bo");void 0!=n&&(m.Pd=n/255);r=R8(r,"fo");void 0!=r&&(m.Rf=r/255);k[l]=m;break;case "ws":k=m.getAttribute("id");c.kw[k]=Z8(this,c,m);break;case "wp":k=m.getAttribute("id"),c.jw[k]=Y8(c,m)}}if(e)for(d={},e=e.childNodes,f=void 0,k=0;k<e.length;k++)switch(l=e[k],l.tagName){case "w":m=
e9(this,c,l);if(l=d[m.id])l.end=m.start;d[m.id]=m;this.g.push(m);break;case "p":var m=c,x=l,z=f,r=[],n=R8(x,"t")||0,u=R8(x,"d")||0,C=x.getAttribute("w")||"0",G=!!f9(x,"a");z&&"\n"==z.text&&!G&&(G=!0);for(var z=G?6:5,J=m.Qk[x.getAttribute("p")],x=x.childNodes,O=0;O<x.length;O++){var Ra=x[O];0<O&&(G=!0);if("s"==Ra.tagName)var bb=Ra,Ra=n,rb=u,Zc=C,cp=G,Ss=z,Ts=bb.textContent?bb.textContent:"",Us=m.Qk[bb.getAttribute("p")],bb=R8(bb,"t")||0,Ra=new g.Fu(Ra+bb,rb-bb,Ss,Zc,Ts,cp,Us);else Ra=new g.Fu(n,u,
z,C,Ra.textContent||"",G,J);r.push(Ra)}if(0<r.length)for(f=r[r.length-1],m=d[r[0].A],m||(m=e9(this,c,l,!0),this.g.push(m)),l=0;l<r.length;l++)n=r[l],r[l].A=m.id,m.Wh.push(n),this.o.push(n)}},t9=function(a){h9.call(this);
this.A={};var b=g.Iu();this.A[b.id]=b;this.g.push(b);for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=g.Iu());var k={};f&&(g.wa(k,f.params),f=f.params.Za)&&
(k.Za={},g.wa(k.Za,f));e.getAttribute("rc")&&(k.Ui=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Er=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.gg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.jh=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ch=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));e.getAttribute("ju")&&(k.textAlign=
(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Bh=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Bh=0));e.getAttribute("bc")&&(k.Za||(k.Za={}),k.Za.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Za||(k.Za={}),k.Za.Pd=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Za||(k.Za={}),k.Za.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.OI=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new g.Gu(c,f,0,e,k)}else c=null}this.A[d]=c;this.g.push(c);break;case "text":for(d=this.o.length,g9(a,b.id,this.o);d<this.o.length;d++)c=this.o[d],(k=this.A[c.A])&&k.Wh.push(c)}a=a.nextSibling}0==this.g.length&&this.g.push(g.Iu())},u9=function(a,b){h9.call(this);
var c=g.Iu(b);this.g.push(c);for(var d=a.firstChild.childNodes,e=0,f=d.length;e<f;e++)g9(d[e],c.id,this.o)},v9=function(a,b,c,d){k9.call(this,d);
c||(c=g.zh(a).hl||"",c=c.split("_").join("-"));this.A=g.Bh(a,{hl:c});this.B=b;this.D={};this.o=null},w9=function(a,b,c,d,e,f){n9.call(this,a,b,c,d,e,f);
g.M(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.U=0;this.ga=window.NaN;this.M=null;this.L=new g.Dd(this.ra,433,this);g.K(this,this.L)},x9=function(a,b,c,d,e,f){n9.call(this,a,b,c,d,e,f);
this.type=1},y9=function(a,b){k9.call(this);
this.A=a;this.$=b;this.o=null},z9=function(a,b,c,d){g.I.call(this);
this.H=b;this.C=new j9;this.g=null;this.G=d;this.o=this.A=null;this.L=c;this.D=new g.Dd(this.F,1E3,this);g.K(this,this.D);b.addEventListener("seekto",this.B,this);this.B(b.getCurrentTime());this.F()},A9=function(a){k9.call(this,a.Bc);
this.o=null;this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},mxa=function(a,b){var c=g.Wa(a.g,(0,g.w)(b.J,b));
-1!=c&&(a.o=c)},B9=function(a,b){switch(b.B){case "asr":l9(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;l9(b,a.g)}},C9=function(a){return a.g?a.g.languageCode:a.o},nxa=function(a){for(var b in a)delete a[b]},D9=function(a,b){return g.aa[a]=b},E9=function(a){g.jm.call(this,a);
g.uu();this.V=g.T(a);this.A=a.getVideoData();this.aa=g.Zt(a);this.$=a;var b=null,c=g.ui("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.vi(c));this.U=b;this.C={Za:{}};this.D={Za:{}};this.H=[];this.G={};this.M={};this.L=!1;this.ga="1"==this.A.C.cc_auto_caps||"1"==this.V.H.cc_auto_caps;c=b=this.B=this.o=this.F=this.J=this.ba=null;g.Ju(this)||(b=new g.Dd(this.Xv,0,this),g.K(this,b),c=new g.Dd(this.kI,2E3,this),g.K(this,c));this.W=b;this.da=c;this.O=new g.om(this);g.K(this,this.O);g.Ju(this)||
this.O.T(a,"resize",this.Lo);this.O.T(a,"onPlaybackAudioChange",this.fE);this.O.T(a,"crn_captions",this.QK,this);this.O.T(a,"crx_captions",this.RK,this);g.Pu(this,g.Qu(this,"display-settings")||{});p9(this)&&this.load()},exa=/^#(?:[0-9a-f]{3}){1,2}$/i,fxa=/#(.)(.)(.)/,hxa=["left",
"right","center"],kxa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,ixa=/(?:\r\n|\r|\n){2,}/,jxa=/^NOTE/,lxa=0,oxa={vn:!0};j9.prototype.contains=function(a){a=g.sb(this.ya,a);return 0<=a||0>a&&1==(-a-1)%2};
j9.prototype.length=function(){return this.ya.length/2};
g.A(k9,g.I);k9.prototype.os=function(a){var b=this.g.o,c=g.Au(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
k9.prototype.hk=function(){return null};
k9.prototype.S=function(){k9.N.S.call(this);this.fe()};
g.A(n9,g.R);g.h=n9.prototype;g.h.jL=function(a,b){var c=g.Kl(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.M(this.element,"ytp-dragging")};
g.h.iL=function(a,b){var c=g.Nl(this.element),d=a-this.ca-.02*this.xa,e=b-this.da-.02*this.sa,f=(d+c.width/2)/this.O*3,f=Math.floor(g.ne(f,0,2)),k=(e+c.height/2)/this.la*3,k=Math.floor(g.ne(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.O,d=100*g.ne(d,0,1),c=(e+k/2*c.height)/this.la,c=100*g.ne(c,0,1);this.A.params.gg=l;this.A.params.Ch=c;this.A.params.jh=d;this.o.gg=l;this.o.Ch=c;this.o.jh=d;this.yh(this.C)};
g.h.hL=function(){g.Kd(this.element,"ytp-dragging")};
g.h.Rb=function(){return this.type};
g.h.yh=function(a){var b=Math.min(this.rs(),this.O),c=this.qs();g.wl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.ym(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.o.jh+2,e=this.o.gg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Ch+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.B.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.wl(this.element,a)};
g.h.ym=function(a){for(var b=0;b<a.length&&a[b]==this.C[b];b++);if(this.H||this.C.length>b)b=0,this.H=!1,this.C=[],this.F=[],this.G=[],this.D=null,g.Pe(this.B);for(;b<a.length;b++)a9(this,a[b])};
g.h.rs=function(){return 0};
g.h.qs=function(){return 0};
g.h.toString=function(){return n9.N.toString.call(this)};
g.A(r9,h9);g.A(s9,h9);g.A(t9,h9);g.A(u9,h9);g.A(v9,k9);g.h=v9.prototype;g.h.kh=g.ba(3);g.h.lh=g.ba(9);g.h.Cf=g.ba(6);g.h.fe=function(){this.o&&this.o.abort()};
g.h.S=function(){this.fe();v9.N.S.call(this)};
g.A(w9,n9);w9.prototype.ra=function(){g.Kd(this.element,"ytp-rollup-mode");var a=this.M;this.M=null;this.yh(a)};
w9.prototype.rs=function(){var a=this.A.params.Er;if(!this.U&&a){var b=g.Le("SPAN");g.Ze(b,"\u00a0"+(0,g.Ha)("\u2014",a)+"\u00a0");g.wl(b,W8(this,this.o.Za));this.B.appendChild(b);this.U=b.offsetWidth;this.B.removeChild(b)}return this.U};
w9.prototype.qs=function(){return this.A.params.Ui*i9(this)};
w9.prototype.yh=function(a){if(i9(this)){for(var b=0,c=0;b<this.C.length&&c<a.length;b++)this.C[b]==a[c]&&c++;var d=m9(a),e=!1,b=0;if(0<c&&c<a.length){var c=this.C.concat(a.slice(c)),f=m9(c)-d;0<f&&(this.M=a,a=c,b-=f,e=!0)}d<this.A.params.Ui&&(b+=this.A.params.Ui-d);e&&!this.L.isActive()&&(g.M(this.element,"ytp-rollup-mode"),this.L.start());b!=this.ga&&(d="",b&&(d="translateY("+Math.ceil(b*i9(this))+"px)"),g.wl(this.B,"transform",d),this.ga=b);w9.N.yh.call(this,a)}else w9.N.yh.call(this,a)};
g.A(x9,n9);x9.prototype.ym=function(a){var b=this.A.Wh;x9.N.ym.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.wa(f,e.o),g.wa(f,oxa),c=e.o,d=f);a9(this,e,f)}};
g.A(y9,k9);g.h=y9.prototype;g.h.kh=g.ba(4);g.h.lh=g.ba(10);g.h.fe=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.Cf=g.ba(7);g.h.S=function(){this.fe();y9.N.S.call(this)};
g.A(z9,g.I);z9.prototype.S=function(){z9.N.S.call(this);this.H.removeEventListener("seekto",this.B,this);this.o&&this.o.abort()};
z9.prototype.B=function(a){this.g=g.Va(this.L.si(a).g)};
z9.prototype.F=function(){this.isDisposed();var a;if(a=null!==this.g)a=this.g,a=a.g.qp(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.H.getCurrentTime())){a=this.g;a=a.g.Fl(a);if(!this.C.contains(a.g[0].A)){var b=g.Nw(g.Ww(a));this.o=g.hi(b,{format:"RAW",$c:(0,g.w)(this.J,this),withCredentials:!0});this.A=a;var b=this.C,c=this.A.g[0].A,d=g.sb(b.ya,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.ya[d-1]&&d<b.ya.length&&1==b.ya[d]-c?(g.eb(b.ya,d),g.eb(b.ya,d-1)):0<d&&1==c-b.ya[d-1]?b.ya[d-1]=c:
d<b.ya.length&&1==b.ya[d]-c?b.ya[d]=c:(g.nb(b.ya,d,0,c),g.nb(b.ya,d+1,0,c)))}this.g=g.Va(a.g)}this.D.start()};
z9.prototype.J=function(a){this.isDisposed();null==a.responseText||400<=a.status||null===this.G||this.G(a.responseText,1E3*this.A.g[0].startTime);this.o=this.A=null};
g.A(A9,k9);g.h=A9.prototype;g.h.kh=g.ba(5);g.h.lh=g.ba(11);g.h.Cf=g.ba(8);g.h.hk=function(){return this.o?this.o.dk:null};
g.h.os=function(){return this.o?this.o.Om:null};
g.h.fe=function(){this.A&&this.A.abort()};
g.h.S=function(){this.fe();A9.N.S.call(this)};
var pxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;A9.prototype.lh=D9(11,function(a,b,c,d){this.B=c;if(this.o=d||null)for(b=0;b<this.o.captionTracks.length;b++)B9(this.g,this.o.captionTracks[b]);a()});
y9.prototype.lh=D9(10,function(a){B9(this.g,new g.Cn({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()});
v9.prototype.lh=D9(9,function(a,b,c){var d=this.A;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.At&&(b.asrs=1);d=g.Bh(d,b);b=(0,g.w)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),r=c,u=e[m].getAttribute("lang_code"),x=e[m].getAttribute("lang_translated"),z=e[m].getAttribute("name"),C=e[m].getAttribute("kind"),G=e[m].getAttribute("id"),J="true"==e[m].getAttribute("lang_default"),
O="true"==e[m].getAttribute("cantran"),Ra=e[m].getAttribute("vss_id");B9(d,new g.Cn({formats:n,format:r,languageCode:u,languageName:x,name:z,kind:C,id:G,is_servable:!0,is_default:J,is_translateable:O,vss_id:Ra}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:r,is_default:u},this.D[l.languageCode]=l.languageName,this.C.push(new g.Bn(l))}a()},this);
this.fe();this.o=g.hi(d,{format:"RAW",Cb:b,withCredentials:!0})});
A9.prototype.Cf=D9(8,function(a){var b=a.H,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.Bh(b,c)});
y9.prototype.Cf=D9(7,function(){return""});
v9.prototype.Cf=D9(6,function(a){var b=this.A,c={v:this.B,type:"track",lang:a.o,name:a.getName(),kind:a.B,fmt:a.A};a.g&&(c.tlang=C9(a));return b=g.Bh(b,c)});
A9.prototype.kh=D9(5,function(a,b){this.isDisposed();var c=this.Cf(a),d=(0,g.w)(function(c){this.A=null;b(c.responseText,a)},this);
this.fe();this.A=g.hi(c,{format:"RAW",Cb:d,withCredentials:!0});this.o&&this.o.dk!=a&&(this.o.Om=a)});
y9.prototype.kh=D9(4,function(a,b){this.fe();var c=this.A.g[a.o];c&&(this.o=new z9(0,this.$,c,function(c,e){b(c,a,e)}))});
v9.prototype.kh=D9(3,function(a,b){this.isDisposed();var c=this.Cf(a),d=(0,g.w)(function(c){this.o=null;b(c.responseText,a)},this);
this.fe();this.o=g.hi(c,{format:"RAW",Cb:d,withCredentials:!0});mxa(this.g,a)});
g.On.prototype.Nj=D9(2,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.m3.prototype.Nj=D9(1,function(){});
g.Cn.prototype.J=D9(0,function(a){return a?this.toString()==a.toString():!1});
g.A(E9,g.jm);g.h=E9.prototype;g.h.S=function(){g.Ju(this)||g.Vu(this,!1);E9.N.S.call(this)};
g.h.load=function(a){E9.N.load.call(this);if(this.o||a)this.B?(a?this.Ou(a,this.B):3!=this.g.Ya()&&this.o.kh(this.B,(0,g.w)(this.Ou,this)),this.g.Ca("captionschanged",g.En(this.B))):this.g.Ca("onCaptionsTrackListChanged");else{var b;this.A.o?b=new y9(this.A.g,this.g):(a=(a=this.A.Rq||this.V.dc||this.A.Fe("yt:cc_default_lang")||this.V.Na)&&a.split("_").join("-"),this.A.captionTracks.length?b=new A9(this.A):b=new v9(this.A.ed,this.A.videoId,a,this.A.Bc));this.o=b;b.lh((0,g.w)(this.kH,this),!0,g.Ju(this)?
"vtt":void 0,this.g.mj())}};
g.h.unload=function(){if(g.Ju(this))for(var a=g.Ae("track",void 0,this.aa.o),b=0;b<a.length;b++)g.Re(a[b]);else g.Fd(this.da),g.Ci(this.g,"captions"),this.H=[],this.o&&this.o.fe(),this.F&&g.Ai(this.g,this.F),this.Lo();E9.N.unload.call(this);(a=g.nv(this.g.app))&&g.MV(a);this.g.Ca("captionschanged",{})};
g.h.kH=function(){var a;if(this.L||b9(this))a=g.Ku(this,this.L);if(g.Ju(this))for(var b=g.Au(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.Dn(d),srclang:C9(d),src:this.o.Cf(d)};d==a&&(e["default"]=1);this.$.app.D.Nj([g.N("TRACK",e)])}else!this.B&&a&&g.Lu(this,a),this.g.Ca("onCaptionsTrackListChanged")};
g.h.Ou=function(a,b,c){if(a){var d;d={};var e=C9(b);e&&(d.lang=e,pxa.test(e)&&(d.Bh=1));d="WEBVTT"==a.substring(0,6)?new r9(a,c||0):(a=g.bp(a))&&a.firstChild?"timedtext"==a.firstChild.tagName?3==(0,window.parseInt)(a.firstChild.getAttribute("format"),10)?new s9(a,d):new t9(a):new u9(a,d):new h9;a={trackName:b.getName(),trackKind:b.B,trackLangCode:C9(b)};b.g&&(a.fromLangCode=b.o);g.rr(this.g,"cc",a);this.B!=this.o.hk()&&(!this.L||g.So(this.V)||g.Uo(this.V)||(g.Fd(this.da),b=g.Iu({gg:0,jh:5,Ch:5,Ui:2,
textAlign:0,Bh:0,lang:"en-GB"}),this.J=[b],a=g.P("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.ba||(c=new g.Mj(g.Kg()),g.K(this,c),this.ba=c.element),c=b.end-b.start,(e=g.Dn(this.B))&&this.J.push(new g.Fu(b.start,c,0,b.id,e)),this.J.push(new g.Fu(b.start,c,0,b.id,a[0]),new g.Fu(b.start,c,0,b.id,this.ba,!0),new g.Fu(b.start,c,0,b.id,a[1],!0)),g.Ai(this.g,this.J),this.da.ce()),(this.L||g.So(this.V))&&g.Ou(this,"module-enabled",!0),(b=g.nv(this.g.app))&&g.MV(b));g.Ai(this.g,d.g.concat(d.o));this.L=
!1}};
g.h.QK=function(a){this.H.push(a);this.W.ce()};
g.h.RK=function(a){g.fb(this.H,a);this.W.ce()};
g.h.$H=function(a){if(a instanceof g.Gu){var b=this.G[a.id];b&&b.A!=a&&(b.dispose(),delete this.G[a.id],b=null);if(!b){var b=this.G,c=a.id;a:{var d=this.aa.Ta(),e=g.Yt(this.aa,!0).height;switch(null!=a.params.ao?a.params.ao:a.params.OI?2:1<a.Wh.length?1:0){case 1:a=new x9(a,this.C,this.D,e,d.width,d.height);break a;case 2:a=new w9(a,this.C,this.D,e,d.width,d.height);break a;default:a=new n9(a,this.C,this.D,e,d.width,d.height)}}b[c]=a}}else b=a.A,this.M[b]||(this.M[b]=[]),this.M[b].push(a)};
g.h.kI=function(){g.Xu(this,this.J);this.J=null};
g.h.Xv=function(){this.W.stop();nxa(this.M);this.H.sort(g.xi);(0,g.F)(this.H,this.$H,this);g.Eb(this.G,function(a,b){!this.M[b]||this.F&&-1==this.F.indexOf(a.A)?(a.dispose(),delete this.G[b]):(a.element.parentNode||g.xs(this.g,a.element,5),a.yh(this.M[b]))},this)};
g.h.Lo=function(){!g.Ju(this)&&this.loaded&&(g.Eb(this.G,function(a,b){a.dispose();delete this.G[b]},this),this.Xv())};
g.h.Zf=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.V.jb&&a.push("stickyLoading","xmlTrack");return a};
g.h.fE=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),p9(this)&&this.load())};
window._exportCheck==g.xa&&g.la("ytmod.player.captions",E9,void 0);})(_yt_player);
